# Generated by Django 5.2.11 on 2026-08-11 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_alter_quiztemplate_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiztemplate',
            name='error_message',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='quiztemplate',
            name='status',
            field=models.CharField(choices=[('pending', 'Hazırlanıyor'), ('ready', 'Hazır'), ('failed', 'Başarısız')], default='ready', max_length=10),
        ),
        migrations.AlterField(
            model_name='quiztemplate',
            name='questions_data',
            field=models.JSONField(default=list),
        ),
    ]
