"""İngilizce konu anlatımları (slug -> metin).

`/en/` sayfalarında gövde içeriği de gerçekten İngilizce olsun diye tutulur;
Türkçe karşılıkları `management/commands/seed_topics.py` içindedir. Yapı iki
dilde bilinçli olarak aynı: giriş → WHEN TO USE → FORM → KEY WORDS → TIPS.
"""

EXPLANATIONS_EN = {
    'present-simple': (
        'The Present Simple is used for general truths, habits, routines and '
        'permanent situations.\n\n'
        'WHEN TO USE IT\n'
        '• Habits and routines: I go to the gym every Monday.\n'
        '• General facts and scientific truths: Water boils at 100°C.\n'
        '• Permanent situations and jobs: She teaches English.\n'
        '• Timetables and schedules: The train leaves at 9 am.\n\n'
        'FORM\n'
        '• Positive: subject + base verb (add -s / -es for he/she/it)\n'
        '    I work · She works · They work\n'
        '• Negative: subject + do/does + not + base verb\n'
        '    I do not (don\'t) work · She does not (doesn\'t) work\n'
        '• Question: Do/Does + subject + base verb?\n'
        '    Do you work? · Does she work?\n\n'
        'THIRD PERSON SPELLING (-s / -es / -ies)\n'
        '• Most verbs take -s: work → works, play → plays\n'
        '• Verbs ending in -s / -ss / -sh / -ch / -x / -o take -es: go → goes, watch → watches, fix → fixes\n'
        '• Consonant + y: drop the y and add -ies: study → studies, try → tries\n'
        '• Vowel + y: no change: play → plays, buy → buys\n'
        '• Irregular: have → has\n\n'
        'COMMON TIME ADVERBS\n'
        'always, usually, often, sometimes, rarely, never, every day, on Mondays, twice a week\n'
        '• The adverb normally goes before the main verb: She often reads.\n'
        '• After the verb "be": She is always late.\n\n'
        'STATE VERBS\n'
        'Verbs such as like, love, hate, know, believe, understand, want, need, own and belong\n'
        'are normally used in the Present Simple, not the Present Continuous:\n'
        '    I am knowing him ❌ → I know him ✅\n\n'
        'TIPS\n'
        '• Don\'t forget the -s in the third person singular.\n'
        '• The verb stays in its base form in negatives and questions: She doesn\'t WORKS ❌ → She doesn\'t WORK ✅\n'
        '• Short answers: Do you…? → Yes, I do. / No, I don\'t.'
    ),
    'present-continuous': (
        'The Present Continuous describes temporary actions happening right now '
        'or around the present moment.\n\n'
        'WHEN TO USE IT\n'
        '• An action in progress as you speak: I am reading a book right now.\n'
        '• Temporary situations these days: She is studying for her exam this week.\n'
        '• Fixed future arrangements: We are meeting Ali tomorrow.\n'
        '• Changing or developing situations: The weather is getting colder.\n\n'
        'FORM\n'
        '• Positive: subject + am/is/are + verb-ing\n'
        '    I am working · She is working · They are working\n'
        '• Negative: subject + am/is/are + not + verb-ing\n'
        '    I am not working · He isn\'t working\n'
        '• Question: Am/Is/Are + subject + verb-ing?\n'
        '    Are you working? · Is she working?\n\n'
        'COMMON TIME EXPRESSIONS\n'
        'now, right now, at the moment, currently, these days, today, this week\n\n'
        'TIPS\n'
        '• Verbs ending in -e drop it: make → making, have → having.\n'
        '• One-syllable verbs ending in vowel + consonant double the consonant: run → running, swim → swimming.\n'
        '• State verbs (know, believe, love, understand, own, belong…) are not normally used in the continuous.'
    ),
    'present-perfect': (
        'The Present Perfect links the past to the present: the action happened '
        'at an unspecified time, or it started in the past and still matters now.\n\n'
        'WHEN TO USE IT\n'
        '• Life experience at an unspecified time: I have been to Paris. (when doesn\'t matter)\n'
        '• A situation that started in the past and continues: She has lived here for ten years.\n'
        '• A recently finished action with a present result: I have just finished my homework.\n'
        '• How many times so far: He has visited us three times.\n\n'
        'FORM\n'
        '• Positive: subject + have/has + past participle (V3)\n'
        '    I have eaten · She has eaten\n'
        '• Negative: subject + have/has + not + V3\n'
        '    I haven\'t eaten · He hasn\'t eaten\n'
        '• Question: Have/Has + subject + V3?\n'
        '    Have you eaten? · Has she eaten?\n\n'
        'KEY WORDS\n'
        'just, already, yet, ever, never, since, for, so far, recently, up to now\n\n'
        'TIPS\n'
        '• "yet" goes in negatives and questions; "already" goes in positives.\n'
        '• "for + a period" (for 5 years) and "since + a starting point" (since 2010).\n'
        '• A finished past time (yesterday, in 2019, last week) needs the Past Simple, not the Present Perfect.'
    ),
    'present-perfect-continuous': (
        'The Present Perfect Continuous describes an action that started in the '
        'past and is still going on, or has just stopped with a visible result.\n\n'
        'WHEN TO USE IT\n'
        '• An action that began earlier and continues: I have been working since morning.\n'
        '• Emphasis on duration: She has been studying for three hours.\n'
        '• A just-finished action with present evidence: Your eyes are red — have you been crying?\n\n'
        'FORM\n'
        '• Positive: subject + have/has been + verb-ing\n'
        '    I have been waiting · She has been waiting\n'
        '• Negative: subject + have/has not been + verb-ing\n'
        '    I haven\'t been waiting\n'
        '• Question: Have/Has + subject + been + verb-ing?\n'
        '    Have you been waiting?\n\n'
        'KEY WORDS\n'
        'for, since, all day, lately, recently, how long\n\n'
        'THE DIFFERENCE\n'
        '• The Present Perfect focuses on the result: I have read the book.\n'
        '• The Present Perfect Continuous focuses on the process and its duration: I have been reading for two hours.'
    ),
    'past-simple': (
        'The Past Simple describes actions that started and finished at a '
        'definite time in the past.\n\n'
        'WHEN TO USE IT\n'
        '• A completed past event: I visited my grandmother yesterday.\n'
        '• A finished period in the past: He worked there from 2015 to 2020.\n'
        '• A sequence of events: She woke up, had breakfast, and went to work.\n'
        '• Past habits: We played in the park every summer.\n\n'
        'FORM\n'
        '• Positive: subject + past form (verb-ed, or an irregular form)\n'
        '    I worked · She went · They ate\n'
        '• Negative: subject + did + not + base verb\n'
        '    I did not (didn\'t) work · She didn\'t go\n'
        '• Question: Did + subject + base verb?\n'
        '    Did you work? · Did she go?\n\n'
        'KEY TIME EXPRESSIONS\n'
        'yesterday, last week, last year, two days ago, in 1990, when I was a child\n\n'
        'TIPS\n'
        '• Irregular verbs have to be learned by heart: go–went, see–saw, have–had, take–took…\n'
        '• The verb returns to its base form in negatives and questions: She didn\'t WENT ❌ → She didn\'t GO ✅\n'
        '• Definite past markers (ago, yesterday) call for the Past Simple, not the Present Perfect.'
    ),
    'past-continuous': (
        'The Past Continuous describes an action that was in progress at a '
        'particular moment in the past.\n\n'
        'WHEN TO USE IT\n'
        '• An action in progress at a past moment: At 8 pm last night, I was watching TV.\n'
        '• Two actions running in parallel: While I was studying, my brother was playing games.\n'
        '• A longer action (Past Continuous) interrupted by a shorter one (Past Simple):\n'
        '    I was cooking when the phone rang.\n'
        '• Setting the background or atmosphere: The sun was shining and birds were singing.\n\n'
        'FORM\n'
        '• Positive: subject + was/were + verb-ing\n'
        '    I was reading · They were reading\n'
        '• Negative: subject + was/were + not + verb-ing\n'
        '    He wasn\'t listening\n'
        '• Question: Was/Were + subject + verb-ing?\n'
        '    Were you watching? · Was she sleeping?\n\n'
        'KEY WORDS\n'
        'while, when, as, at that moment, all day, at 8 pm yesterday'
    ),
    'past-perfect': (
        'The Past Perfect shows which of two past events happened first — the '
        '"past before the past".\n\n'
        'WHEN TO USE IT\n'
        '• An event that happened before another past event:\n'
        '    When I arrived, she had already left. (she left BEFORE I arrived)\n'
        '• Making the order of events clear: By 8 pm they had finished dinner.\n'
        '• Shifting the Past Simple back one step in reported speech.\n\n'
        'FORM\n'
        '• Positive: subject + had + past participle (V3)\n'
        '    I had eaten · She had gone\n'
        '• Negative: subject + had + not + V3\n'
        '    I hadn\'t eaten\n'
        '• Question: Had + subject + V3?\n'
        '    Had you eaten?\n\n'
        'KEY WORDS\n'
        'already, just, yet, by the time, before, after, when, until\n\n'
        'TIPS\n'
        '• If you are talking about a single past event, the Past Simple is enough — use the Past Perfect '
        'only when you need to show that one of two events came first.'
    ),
    'future-simple-will': (
        '"Will" is used for predictions, decisions made at the moment of '
        'speaking, promises and offers.\n\n'
        'WHEN TO USE IT\n'
        '• A spontaneous decision: I\'m thirsty — I\'ll get some water.\n'
        '• A prediction: It will rain tonight.\n'
        '• A promise: I will always love you.\n'
        '• An offer or a request: I will help you. / Will you pass the salt?\n\n'
        'FORM\n'
        '• Positive: subject + will + base verb (I\'ll / she\'ll / they\'ll)\n'
        '• Negative: subject + will not (won\'t) + base verb\n'
        '• Question: Will + subject + base verb?\n\n'
        'TIPS\n'
        '• For something you have already planned, "be going to" fits better: I am going to study tonight.\n'
        '• Don\'t use "will" in time clauses: When he arrives (not "will arrive"), I will call you.'
    ),
    'future-be-going-to': (
        '"Be going to" is used for intentions decided in advance and for '
        'predictions based on present evidence.\n\n'
        'WHEN TO USE IT\n'
        '• A plan decided beforehand: I am going to travel to Italy next month.\n'
        '• A prediction based on what you can see: Look at those clouds — it is going to rain.\n\n'
        'FORM\n'
        '• Positive: subject + am/is/are + going to + base verb\n'
        '    I am going to study · She is going to study\n'
        '• Negative: subject + am/is/are + not + going to + base verb\n'
        '• Question: Am/Is/Are + subject + going to + base verb?\n\n'
        'WILL vs BE GOING TO\n'
        '• "will": a spontaneous decision, a general prediction, a promise\n'
        '• "be going to": a prior plan, a prediction based on visible evidence\n'
        '• In everyday speech the two are often interchangeable.'
    ),
    'modals-can-could': (
        '"Can" and "could" are modal verbs expressing ability, permission, '
        'requests and possibility.\n\n'
        'HOW THEY ARE USED\n'
        '• can → present ability: I can swim.\n'
        '• could → past ability: When I was young, I could run fast.\n'
        '• can / could → permission: Can I open the window? / Could I open the window? (could is more polite)\n'
        '• can / could → requests: Can you help me? / Could you help me? (could is more polite)\n'
        '• could → tentative possibility: It could rain tomorrow.\n\n'
        'FORM\n'
        '• Positive: subject + can / could + base verb\n'
        '• Negative: subject + cannot (can\'t) / could not (couldn\'t) + base verb\n'
        '• Question: Can / Could + subject + base verb?\n\n'
        'TIPS\n'
        '• The verb after a modal stays in its base form: She can WORKS ❌ → She can WORK ✅\n'
        '• "could have + V3" means something was possible but didn\'t happen: You could have called me.'
    ),
    'modals-must-should': (
        '"Must" expresses strong obligation and confident deduction; "should" '
        'expresses advice and expectation.\n\n'
        'HOW THEY ARE USED\n'
        '• must → obligation you impose on yourself: I must finish this report today.\n'
        '• must → strong deduction: He must be tired. (you are almost certain)\n'
        '• must not → prohibition: You must not smoke here.\n'
        '• should → advice: You should exercise more.\n'
        '• should → expectation: The train should arrive at 8.\n'
        '• should not → something inadvisable: You shouldn\'t eat so much sugar.\n\n'
        'FORM\n'
        '• subject + must / should + base verb\n'
        '• Negative: must not (mustn\'t) / should not (shouldn\'t) + base verb\n'
        '• Question: Must / Should + subject + base verb?\n\n'
        'MUST vs HAVE TO\n'
        '• must: an obligation that comes from the speaker or from a rule\n'
        '• have to: an obligation imposed from outside (rules, your job…)\n'
        '• The negatives differ: "mustn\'t" = it is forbidden / "don\'t have to" = it isn\'t necessary'
    ),
    'conditional-0': (
        'The Zero Conditional describes things that are always true: scientific '
        'facts, general truths and rules.\n\n'
        'WHEN TO USE IT\n'
        '• Scientific facts: If you heat water to 100°C, it boils.\n'
        '• General truths: If it rains, the ground gets wet.\n'
        '• Rules and instructions: If you press this button, the door opens.\n\n'
        'FORM\n'
        '• If + Present Simple, Present Simple.\n'
        '    If you mix red and blue, you get purple.\n'
        '• The order can be reversed:\n'
        '    You get purple if you mix red and blue.\n\n'
        'TIPS\n'
        '• You can replace "if" with "when", because the result is practically certain:\n'
        '    When you heat water, it boils.\n'
        '• There is no "will" or "would" here — both halves stay in the Present Simple.'
    ),
    'conditional-1': (
        'The First Conditional is used for realistic situations that are likely '
        'to happen in the future.\n\n'
        'WHEN TO USE IT\n'
        '• A realistic future possibility: If it rains tomorrow, we will stay home.\n'
        '• Warnings and plans: If you don\'t hurry, you will miss the bus.\n'
        '• Promises and offers: If you help me, I will help you.\n\n'
        'FORM\n'
        '• If + Present Simple, will + base verb\n'
        '    If you call me, I will answer.\n'
        '• Either order works:\n'
        '    I will answer if you call me.\n\n'
        'TIPS\n'
        '• Never use "will" in the "if" clause:\n'
        '    If it WILL rain ❌ → If it RAINS ✅\n'
        '• Other modals can replace "will": may, might, can, should.\n'
        '    If you study, you may pass.\n'
        '• Comma rule: use one when the "if" clause comes first; usually not when it comes second.'
    ),
    'conditional-2': (
        'The Second Conditional is used for imaginary, unreal or very unlikely '
        'situations in the present or future.\n\n'
        'WHEN TO USE IT\n'
        '• An impossible or imaginary situation: If I had wings, I would fly.\n'
        '• A remote possibility: If I won the lottery, I would buy an island.\n'
        '• Giving advice: If I were you, I would apologize.\n\n'
        'FORM\n'
        '• If + Past Simple, would + base verb\n'
        '    If he came, he would see the show.\n'
        '• With I / he / she / it, "were" is usually preferred (and is more formal):\n'
        '    If I were rich… / If she were here…\n'
        '• Negative: If I didn\'t have work, I wouldn\'t stay.\n\n'
        'TIPS\n'
        '• Never use "would" in the "if" clause: If I WOULD have ❌ → If I HAD ✅\n'
        '• "could" or "might" can replace "would":\n'
        '    If I had more time, I could travel more.\n'
        '• "If I were you" is the polite way to give advice.'
    ),
    'conditional-3': (
        'The Third Conditional describes imaginary situations in the past — '
        'things that did not happen, and often regrets.\n\n'
        'WHEN TO USE IT\n'
        '• Regret about the past: If I had studied harder, I would have passed.\n'
        '• An imaginary past result: If he had left earlier, he would have caught the train.\n'
        '• Criticism: If you had told me, I would have helped.\n\n'
        'FORM\n'
        '• If + Past Perfect, would have + past participle (V3)\n'
        '    If I had known, I would have come.\n'
        '• Negative: If you hadn\'t called me, I wouldn\'t have found out.\n\n'
        'TIPS\n'
        '• Never write "would have" in the "if" clause: If I WOULD have known ❌ → If I HAD known ✅\n'
        '• "could have" and "might have" can replace "would have":\n'
        '    If we had left earlier, we could have arrived on time.\n'
        '• This structure is only for the past — the situation can no longer change.'
    ),
    'passive-voice': (
        'The passive voice is used when the action itself, or the thing affected '
        'by it, matters more than who performed it.\n\n'
        'WHEN TO USE IT\n'
        '• The doer is unknown or unimportant: The window was broken.\n'
        '• The object or the effect is the point: The project was completed last week.\n'
        '• It is very common in scientific and formal writing: Water is heated to 100°C.\n\n'
        'FORM (in every tense): subject + be (in that tense) + past participle (V3)\n'
        '• Present Simple: is/are + V3 → The room is cleaned every day.\n'
        '• Past Simple: was/were + V3 → The letter was sent.\n'
        '• Present Perfect: has/have been + V3 → The door has been repaired.\n'
        '• Future: will be + V3 → The results will be announced.\n'
        '• Modal: can/should be + V3 → The problem can be solved.\n\n'
        'TIPS\n'
        '• If the doer matters, add it with "by": The book was written by George Orwell.\n'
        '• Intransitive verbs (go, arrive, sleep…) have no passive form.\n'
        '• Don\'t overuse it: in everyday writing the active voice is usually clearer.'
    ),
    'reported-speech': (
        'Reported speech is used to tell someone what another person said '
        'without quoting them directly. The tense usually shifts one step back.\n\n'
        'TENSE SHIFTS\n'
        '• Present Simple → Past Simple\n'
        '• Present Continuous → Past Continuous\n'
        '• Present Perfect → Past Perfect\n'
        '• Past Simple → Past Perfect\n'
        '• will → would\n'
        '• can → could\n'
        '• must → had to\n\n'
        'PRONOUNS AND TIME WORDS CHANGE\n'
        '• I → he/she, we → they, my → his/her\n'
        '• now → then, today → that day, yesterday → the day before, tomorrow → the next day\n\n'
        'FORM\n'
        '• Statement: He said (that) + the shifted sentence.\n'
        '    "I am tired." → He said (that) he was tired.\n'
        '• Question: He asked + question word / if + the shifted clause.\n'
        '  (The auxiliary disappears and the word order becomes that of a statement!)\n'
        '    "Where do you live?" → He asked where I lived.\n'
        '    "Are you OK?" → He asked if I was OK.\n\n'
        'TIPS\n'
        '• "say" takes no object, "tell" does: He said (to me)… / He told me…\n'
        '• Universal truths need not shift: He said the Earth revolves around the Sun.'
    ),
    'comparatives-superlatives': (
        'Comparatives and superlatives are used to compare two or more things.\n\n'
        'RULES\n'
        '• One-syllable adjectives → -er / -est: tall → taller → the tallest, fast → faster → the fastest\n'
        '• Two syllables ending in -y → drop the y, add -ier / -iest: happy → happier → the happiest\n'
        '• Adjectives of two or more syllables → more / the most: beautiful → more beautiful → the most beautiful\n'
        '• Irregular: good → better → the best, bad → worse → the worst, far → farther/further → the farthest\n\n'
        'FORM\n'
        '• Comparative: X + is/are + adjective-er (or more + adjective) + than + Y\n'
        '    This car is faster than that one.\n'
        '    This movie is more interesting than the book.\n'
        '• Superlative: X + is/are + the + adjective-est (or the most + adjective) + group\n'
        '    She is the tallest in the class.\n'
        '    This is the most expensive watch in the store.\n\n'
        'EQUALITY AND INEQUALITY\n'
        '• as + adjective + as → an equal comparison: He is as tall as his brother.\n'
        '• not as + adjective + as → less than: This test is not as hard as the previous one.\n\n'
        'TIPS\n'
        '• A superlative is normally preceded by "the".\n'
        '• Never combine -er and "more": more taller ❌ → taller ✅'
    ),
}
