# Generated by Django 5.2.11 on 2026-08-02 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='explanation_en',
            field=models.TextField(blank=True, verbose_name='Konu anlatımı (EN)'),
        ),
        migrations.AddField(
            model_name='topic',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='explanation',
            field=models.TextField(blank=True, verbose_name='Konu anlatımı (TR)'),
        ),
    ]
