# Generated by Django 5.2.11 on 2026-04-16 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='mastered',
            field=models.BooleanField(default=False),
        ),
    ]
