# Generated by Django 5.2.11 on 2026-04-16 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_category', models.CharField(choices=[('software_dev', 'Yazılım Geliştirme'), ('computer_mgmt', 'Bilgisayar Yönetimi'), ('info_systems', 'Bilişim Sistemleri'), ('network_systems', 'Ağ Sistemleri'), ('database_admin', 'Veri Tabanı Yönetimi'), ('cyber_security', 'Siber Güvenlik'), ('devops', 'DevOps / Sistem Yönetimi'), ('project_mgmt', 'Proje Yönetimi'), ('ai_ml', 'Yapay Zeka / Makine Öğrenmesi'), ('web_dev', 'Web Geliştirme'), ('mobile_dev', 'Mobil Uygulama Geliştirme'), ('data_science', 'Veri Bilimi / Analitik'), ('cloud', 'Bulut Bilişim'), ('custom', 'Özel (kendi yazdığın)')], default='custom', max_length=30)),
                ('custom_title', models.CharField(blank=True, max_length=200)),
                ('questions_data', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
