# Generated by Django 5.2.11 on 2026-04-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='cv_filename',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='source',
            field=models.CharField(choices=[('category', 'Kategori'), ('custom', 'Özel başlık'), ('cv', 'CV yükleme')], default='category', max_length=10),
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='job_category',
            field=models.CharField(choices=[('backend_dev', 'Backend Developer'), ('frontend_dev', 'Frontend Developer'), ('python_fullstack', 'Python Full Stack Developer'), ('dotnet_fullstack', '.NET Full Stack Developer'), ('java_fullstack', 'Java Full Stack Developer'), ('nodejs_fullstack', 'Node.js Full Stack Developer'), ('react_dev', 'React Developer'), ('angular_dev', 'Angular Developer'), ('vue_dev', 'Vue.js Developer'), ('go_dev', 'Go (Golang) Developer'), ('rust_dev', 'Rust Developer'), ('php_dev', 'PHP / Laravel Developer'), ('ios_dev', 'iOS Developer (Swift)'), ('android_dev', 'Android Developer (Kotlin)'), ('flutter_dev', 'Flutter / Dart Developer'), ('software_dev', 'Yazılım Geliştirme (Genel)'), ('devops', 'DevOps / SRE'), ('cloud', 'Bulut Bilişim (AWS/Azure/GCP)'), ('cyber_security', 'Siber Güvenlik'), ('ai_ml', 'Yapay Zeka / Makine Öğrenmesi'), ('data_science', 'Veri Bilimi / Veri Mühendisliği'), ('database_admin', 'Veri Tabanı Yönetimi (DBA)'), ('network_systems', 'Ağ Sistemleri'), ('info_systems', 'Bilişim Sistemleri'), ('computer_mgmt', 'Bilgisayar Yönetimi'), ('project_mgmt', 'Proje Yönetimi / Scrum Master'), ('qa_test', 'QA / Test Mühendisliği'), ('mobile_dev', 'Mobil Uygulama Geliştirme (Genel)'), ('web_dev', 'Web Geliştirme (Genel)'), ('embedded', 'Gömülü Sistemler'), ('game_dev', 'Oyun Geliştirme'), ('custom', 'Özel (kendi yazdığın)')], default='custom', max_length=30),
        ),
    ]
