# Generated by Django 5.2.11 on 2026-08-10 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0003_clean_empty_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='error_message',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='status',
            field=models.CharField(choices=[('pending', 'Hazırlanıyor'), ('ready', 'Hazır'), ('failed', 'Başarısız')], default='ready', max_length=10),
        ),
    ]
