# Generated by Django 5.2.11 on 2026-04-15 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1')], db_index=True, max_length=2)),
                ('rank', models.PositiveIntegerField()),
                ('english', models.CharField(max_length=120)),
                ('part_of_speech', models.CharField(blank=True, max_length=40)),
                ('turkish', models.CharField(max_length=400)),
                ('example_en', models.CharField(blank=True, max_length=500)),
                ('example_tr', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['level', 'rank'],
                'constraints': [models.UniqueConstraint(fields=('level', 'english', 'part_of_speech'), name='unique_bank_word')],
            },
        ),
        migrations.CreateModel(
            name='BankProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mastered', models.BooleanField(default=False)),
                ('wrong_count', models.PositiveIntegerField(default=0)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('last_answered_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_progress', to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='wordbank.bankword')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'word'), name='unique_user_word_progress')],
            },
        ),
    ]
