# Generated by Django 5.2.11 on 2026-04-16 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordbank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankword',
            name='level',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], db_index=True, max_length=2),
        ),
    ]
